# https://taskfile.dev

version: '3'

tasks:
  install:
    cmds:
      - ./essentials/install.sh
      - ./utilities/install.sh
  install-with-rtl88x2bu:
    cmds:
      - task: essentials:install
      - task: utilities:install

