# https://taskfile.dev

version: '3'

tasks:
  install:
    cmds:
      - sudo apt install
        curl 
        jq 
        htop 
        neofetch 
        hugo 
        variety 
        gnome-tweak-tool 
        -y
      - sudo snap install
        spotify
        telegrap-desktop
      - sudo snap install
        go
        code
        emacs
        espanso
        --classic
