# https://taskfile.dev

version: '3'

tasks:
  install:
    dir: /tmp
    cmds:
      - curl -LJ https://github.com/ankitects/anki/releases/download/2.1.38/anki-2.1.38-linux.tar.bz2 -o anki.tar.bz2
      - tar xjf ./anki.tar.bz2
      - cd anki-2.1.38-linux/
      - sudo ./install.sh
