# https://taskfile.dev

version: '3'

tasks:
  install:
    dir: /tmp
    cmds:
      - rm ./JetBrainsMono.zip
      - curl -LOJ https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
      - unzip JetBrainsMono.zip -d ./fonts
      - mkdir -p ~/.local/share/fonts
      - cp ./fonts/* ~/.local/share/fonts/
      - fc-cache -f -v
