# https://taskfile.dev

version: '3'

tasks:
  install:
    dir: /tmp
    cmds:
      - curl -LJ https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.19.7784.tar.gz -o jetbrains-toolbox.tar.gz
      - tar -xvf ./jetbrains-toolbox.tar.gz
      - cd ./jetbrains-toolbox-1.19.7784
      - ./jetbrains-toolbox
