# https://taskfile.dev

version: '3'

tasks:
  install:
    cmds:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py |
        python3
      - source $HOME/.poetry/env
      - zsh -c 'mkdir $ZSH/plugins/poetry'
      - zsh -c 'poetry completions zsh > $ZSH/plugins/poetry/_poetry'
