# https://taskfile.dev

version: '3'

tasks:
  dir: /tmp
  install:
    cmds:
      - curl -LOJ https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo apt install ./google-chrome-stable_current_amd64.deb
