# https://taskfile.dev

version: '3'

tasks:

  install:
    cmds:
      - git clone https://github.com/asdf-vm/asdf.git ~/.asdf
      - cd ~/.asdf
      - git checkout "$(git describe --abbrev=0 --tags)"

  install-nodejs:
    cmds:
      - sudo apt install gpg dirmngr
      - bash -c "${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring"
      - asdf install nodejs latest:lts
      - asdf global nodejs lts

