# https://taskfile.dev

version: '3'

tasks:
  install:
    dir: /tmp
    cmds:
      - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo apt install ./packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt update
      - sudo apt install apt-transport-https dotnet-sdk-5.0 -y
      - dotnet install --global dotnet-ef
      - dotnet tool install --global Microsoft.Web.LibraryManager.Cli

