# https://taskfile.dev

version: '3'

tasks:
  hide-tabs:
    cmds:
      - echo "#######################################################################"
      - echo "# Please enable legacy custom style of Firefox after the operation... #"
      - echo "#######################################################################"
      - cd $HOME/.mozilla/firefox/*.default-release
      - mkdir -p chrome
      - tee -a chrome/userChrome.css << "#TabsToolbar { visibility: collapse !important; }"
